export const AUTHUSER = {
  id: "u72-8391-qx",
  firstName: "John",
  middleName: "Quincy",
  lastName: "Adams",
  dateOfBirth: "1990-05-15",
  gender: "male",
  phone: "555-123-4567",
  email: "john.adams@example.com",
  address: "123 Healthcare Lane, Medical District, NY 10001",
  language: "english",
  nationality: "American",
  emergencyContact: "Abigail Adams: +1 (555) 987-6543",
  religion: "Christianity",
};

export const GENDER = [
  { name: "male", value: "male" },
  { name: "female", value: "female" },
];

export const LANGUAGES = [
  { name: "English", value: "english" },
  { name: "Spanish", value: "spanish" },
  { name: "French", value: "french" },
  { name: "German", value: "german" },
  { name: "Chinese", value: "chinese" },
  { name: "Arabic", value: "arabic" },
  { name: "Hindi", value: "hindi" },
  { name: "Portuguese", value: "portuguese" },
  { name: "Russian", value: "russian" },
  { name: "Japanese", value: "japanese" },
  { name: "Thai", value: "thai" },
];

export const PATIENTS: User[] = [
  {
    id: "pat-001",
    firstName: "Liam",
    middleName: "James",
    lastName: "Smith",
    dateOfBirth: "1988-03-12",
    gender: "male",
    phone: "+1 (555) 010-9988",
    email: "liam.smith@email.com",
    address: "742 Evergreen Terrace, Springfield, IL 62704",
    language: "english",
    nationality: "American",
    emergencyContact: "Mary Smith: +1 (555) 010-9900",
    religion: "Christianity",
  },
  {
    id: "pat-002",
    firstName: "Yuki",
    lastName: "Tanaka",
    dateOfBirth: "1994-07-25",
    gender: "female",
    phone: "+81 90-1234-5678",
    email: "y.tanaka@jp-health.com",
    address: "2-chōme-1-1 Nihonbashimuromachi, Chuo City, Tokyo 103-0022",
    language: "japanese",
    nationality: "Japanese",
    emergencyContact: "Kenji Tanaka: +81 90-8888-7777",
  },
  {
    id: "pat-003",
    firstName: "Amara",
    middleName: "Abebe",
    lastName: "Bekele",
    dateOfBirth: "1991-11-05",
    gender: "female",
    phone: "+251 11 123 4567",
    email: "amara.bekele@care.et",
    address: "Bole Sub City, Kebele 03, Addis Ababa, Ethiopia",
    language: "amharic",
    nationality: "Ethiopian",
    emergencyContact: "Abebe Bekele: +251 91 100 0000",
    religion: "Orthodox",
  },
  {
    id: "pat-004",
    firstName: "Sofia",
    lastName: "García",
    dateOfBirth: "1982-01-19",
    gender: "female",
    phone: "+34 912 34 56 78",
    email: "sofia.garcia@medico.es",
    address: "Paseo de la Castellana, 259, 28046 Madrid, Spain",
    language: "spanish",
    nationality: "Spanish",
    emergencyContact: "Luis García: +34 600 11 22 33",
  },
  {
    id: "pat-005",
    firstName: "Arjun",
    middleName: "Vikram",
    lastName: "Mehta",
    dateOfBirth: "1975-09-30",
    gender: "male",
    phone: "+91 22 2345 6789",
    email: "arjun.mehta@clinic.in",
    address: "Marine Drive, Mumbai, Maharashtra 400020, India",
    language: "hindi",
    nationality: "Indian",
    emergencyContact: "Priya Mehta: +91 98200 12345",
    religion: "Hinduism",
  },
];

export const ADMIN_FILTERS = [
  { name: "Newest", value: "newest" },
  { name: "Oldest", value: "oldest" },
];
